import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { FaInstagram, FaWhatsapp } from "react-icons/fa";
import { FiGithub, FiLinkedin } from "react-icons/fi";
import Cover from '../components/cover';
import About from '../components/about';
import Portofolio from '../components/portofolio';
import Skills from '../components/skills';
import Header from '../components/header';


const Home = () => {
  return (
    <div className="scroll-smooth">
      <Head>
        <title>Yudistira Maulana</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="p-10 pb-[200px] max-w-2xl m-auto text-gray-400 ">
        <Cover />
        <About />
        <Skills />
        <Portofolio />
      </main>

      <footer className=""></footer>
    </div>
  );
};

export default Home;
