import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { FaInstagram, FaWhatsapp } from "react-icons/fa";
import { FiGithub, FiLinkedin } from "react-icons/fi";

const portofolio = [
  {
    cover: "/campus-connect.jpg",
    namaProject: "Campus Connect",
    desc: "Social media khusus untuk para mahasiswa seluruh indonesia",
    demo: "https://campus-connects.netlify.app/",
    sc: "https://github.com/Yudistir4/campus-connect-fe",
  },
  {
    cover: "/wedding-invitation.jpg",
    namaProject: "Wedding Invitation",
    desc: "Undangan pernikahan online",
    demo: "https://invitation-aji-nike.netlify.app/?to=Nama+tamu",
    sc: "https://github.com/Yudistir4/wedding-invitation",
  },
];

const sosmed = {
  ig: "https://www.instagram.com/yudistira_maulana",
  linkedin: "https://www.linkedin.com/in/yudistira-maulana-66547b1b0/",
  github: "https://github.com/Yudistir4",
  wa: "https://api.whatsapp.com/send/?phone=6282258864709",
};

const Home = () => {
  return (
    <div className="scroll-smooth">
      <Head>
        <title>Yudistira Maulana</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex items-center justify-center bg-[#0A192F]/50 w-full h-14 fixed  backdrop-blur-sm shadow-lg shadow-[#0A192F] gap-8 px-5 z-50">
        {/* <div className="flex-1"></div> */}
        <a
          href="#home"
          className="font-semibold text-white hover:text-emerald-400 transition"
        >
          Home
        </a>
        <a
          href="#about"
          className="font-semibold text-white hover:text-emerald-400 transition"
        >
          About
        </a>
        <a
          href="#portofolio"
          className="font-semibold text-white hover:text-emerald-400 transition"
        >
          Portofolio
        </a>
      </header>
      <main className="p-10 pb-[200px] max-w-2xl m-auto text-gray-400 ">
        <div
          className="h-[100vh] w-full flex flex-col items-center justify-center gap-3"
          id="home"
        >
          <Image
            src="/profilePic.jpg"
            className="rounded-full w-[50px] h-[50px]"
            // layout="fill"
            alt="profile"
            width={"100px"}
            height={"100px"}
          />
          <div className="flex flex-col items-center justify-center">
            <h1 className="text-2xl font-bold text-gray-200">
              Yudistira Maulana
            </h1>
            <p className="text-gray-300">I'm Fullstack developer</p>
          </div>
          <div className="flex items-center">
            <a
              href={sosmed.ig}
              target="_blank"
              className="h-10 w-10 rounded-full group hover:text-emerald-500 transition text-gray-100 flex items-center justify-center"
              rel="noreferrer"
            >
              <FaInstagram
                size={20}
                className="group-hover:mb-2 transition-all"
              />
            </a>
            <a
              href={sosmed.linkedin}
              target="_blank"
              rel="noreferrer"
              className="h-10 w-10 rounded-full group hover:text-emerald-500 transition text-gray-100 flex items-center justify-center"
            >
              <FiLinkedin
                size={20}
                className="group-hover:mb-2 transition-all"
              />
            </a>
            <a
              href={sosmed.github}
              target="_blank"
              rel="noreferrer"
              className="h-10 w-10 rounded-full group hover:text-emerald-500 transition text-gray-100 flex items-center justify-center"
            >
              <FiGithub size={20} className="group-hover:mb-2 transition-all" />
            </a>
            <a
              href={sosmed.wa}
              target="_blank"
              rel="noreferrer"
              className="group-hover-10 w-10 rounded-full group hover:text-emerald-500 transition text-gray-100 flex items-center justify-center"
            >
              <FaWhatsapp
                size={20}
                className="group-hover:mb-2 transition-all"
              />
            </a>
          </div>
        </div>
        <div className="pt-20" id="about">
          <div className="flex items-center mb-3">
            <h2 className="shrink-0 text-2xl font-bold text-gray-100">
              About Me
            </h2>
            <div className="ml-3 h-[1px] flex-1 bg-slate-600"></div>
          </div>
          <p className="text-gray-400 text-justify">
            Hello! My name is Yudis, you can call me Yudis, Acong or whatever
            you want. I'm a Fullstack Developer located in West Java, Indonesia
            and I enjoy creating things that live on the internet.
            <br />
            <br />
            Here are a few technologies I’ve been working with recently:
          </p>
          <div className="flex gap-20">
            <ul className="list-disc list-inside text-gray-400 ">
              <li>React</li>
              <li>Next js</li>
              <li>Node.js</li>
              <li>Mongodb</li>
              <li>Typescript</li>
            </ul>
            <ul className="list-disc list-inside text-gray-400 ">
              <li>Tailwind</li>
              <li>Chakra UI</li>
              <li>Material UI</li>
              <li>Express js</li>
              <li>Firebase</li>
            </ul>
          </div>
        </div>
        <div className="mt-20 pt-20" id="portofolio">
          <div className="flex items-center mb-3">
            <h2 className="shrink-0 text-2xl font-bold text-gray-100">
              Portofolio
            </h2>
            <div className="ml-3 h-[1px] flex-1 bg-slate-600"></div>
          </div>
        </div>
        <div className="grid grid-cols-1 xs:grid-cols-2 gap-3">
          {portofolio.map((val) => (
            <div
              key={val.namaProject}
              className="bg-card w-full p-5 rounded-md flex flex-col gap-3"
            >
              <div className="group rounded-md relative aspect-[3/2] overflow-hidden">
                <Image
                  src={val.cover}
                  layout="fill"
                  objectFit="cover"
                  alt="test"
                  // width={50}
                  // height={50}
                  className="  duration-300 transition-all  "
                />
                <div className="backdrop-grayscale group-hover:backdrop-grayscale-0 group-hover:bg-emerald-400/0 transition z-10 bg-emerald-500/40 absolute w-full h-full duration-300"></div>
              </div>
              <h3 className="text-gray-100 font-semibold text-lg hover:text-emerald-400">
                {val.namaProject}
              </h3>
              <p>{val.desc}</p>
              <div className="flex-1"></div>
              <div className="grid grid-cols-2 gap-2">
                <a
                  href={val.sc}
                  className="text-center transition font-semibold px-3 py-2 rounded-full border-[1px] hover:bg-emerald-400/10 border-emerald-400 text-emerald-400 cursor-pointer"
                  target="_blank"
                  rel="noreferrer"
                >
                  CODE
                </a>
                <a
                  href={val.demo}
                  className="text-center transition font-semibold px-3 py-2 rounded-full border-[1px] hover:bg-emerald-400/10 border-emerald-400 text-emerald-400 cursor-pointer"
                  target="_blank"
                  rel="noreferrer"
                >
                  DEMO
                </a>
              </div>
            </div>
          ))}
        </div>
      </main>

      <footer className=""></footer>
    </div>
  );
};

export default Home;
